export const portfolioData = {
  name: "Aziz Ouhibi",
  age:22,
  title: "Software Engineering Student | Backend, Mobile and CI/CD Developer",
  location: "Ariana, Tunisia",
  email: "ouhibi.aziz@esprit.tn",
  phone: "+216 93 177 115",
  github: "https://github.com/azizwhibi",
  linkedin: "https://www.linkedin.com/in/azizouhibi/",
  hero: {
    headline: "Building reliable mobile apps, backend services, and automated delivery pipelines.",
    description:
      "Software engineering student focused on backend development, cross-platform and native mobile applications, REST APIs, CI/CD automation, Docker, and cloud-oriented engineering practices.",
    ctaPrimary: "View My Projects",
    ctaSecondary: "Get In Touch",
  },
  about: {
    summary:
      "I am a software engineering student at ESPRIT with practical experience in mobile, backend, and CI/CD development. I enjoy taking software from early requirements through implementation, testing, debugging, and delivery.",
    experience:
      "I have worked on React Native and Flutter applications, native Android and iOS development, NestJS and Flask backend services, REST API design, JWT authentication, database integration, Docker-based development, GitHub Actions automation, and CI/CD monitoring workflows.",
    interests:
      "I am interested in backend engineering, mobile development, cloud computing, DevOps, software quality, system reliability, and secure delivery practices.",
  },
  experience: [
    {
      role: "Part-Time Software Developer",
      company: "WeHackLabs",
      location: "Tunis, Tunisia",
      period: "September 2025 – Present",
      responsibilities: [
        "I delivered features, tests, and debugging work for client and internal web applications.",
        "I built a responsive Progressive Web App for desktop and mobile.",
        "I participated in requirements analysis and prioritisation within an Agile team.",
      ],
    },
    {
      role: "Software Engineering Intern",
      company: "Tunisie Telecom",
      location: "Tunis, Tunisia",
      period: "June 2026 – August 2026",
      responsibilities: [
        "I built a Flask REST API and dashboard to centralise CI/CD data.",
        "I automated four GitHub Actions workflows for metrics, anomaly detection, and deployment.",
        "I created Docker Compose health checks and diagnostic workflows for CI/CD pipelines.",
        "I automated workflows that saved approximately 15 hours per month.",
      ],
    },
    {
      role: "Mobile Developer Intern",
      company: "ArabSoft",
      location: "Tunis, Tunisia",
      period: "June 2025 – August 2025",
      responsibilities: [
        "I developed a complete React Native application in two months, from requirements analysis to production.",
        "I built secure sign-up and login flows.",
        "I developed a chatbot covering more than five categories.",
        "I delivered 100% of planned features through iterative development and user feedback.",
      ],
    },
  ],
  projects: [
    {
      name: "Karhebti Android",
      fullTitle: "Karhebti Android — Vehicle Maintenance Management App",
      period: "November 2025 – February 2026",
      platforms: "Android",
      technologies: ["Kotlin", "Jetpack Compose", "Material Design 3", "MongoDB", "Retrofit", "OkHttp", "JWT"],
      description: "A modern Android application for managing vehicle maintenance, documents, and garage appointments with beautiful Material Design 3 UI.",
      keyFeatures: [
        "Native Android application with Kotlin and Jetpack Compose",
        "Material Design 3 UI with modern rounded corners and shadows",
        "MongoDB data storage",
        "JWT-based authentication",
        "Vehicle tracking and management",
        "Maintenance scheduling and history",
        "Garage search and booking functionality",
        "Document upload and management",
        "French localization and date formatting",
      ],
      tags: ["Kotlin", "Jetpack Compose", "Material Design 3", "MongoDB", "Retrofit", "OkHttp", "JWT", "Android", "Mobile Development", "Car Management"],
      github: "https://github.com/karhebti-app/karhebti-android",
      linkStatus: "Link coming soon",
    },
    {
      name: "Karhebti iOS",
      fullTitle: "Karhebti iOS — Vehicle Maintenance and Tracking App",
      period: "November 2025 – February 2026",
      platforms: "iOS",
      technologies: ["Swift", "SwiftUI", "NestJS", "MongoDB", "JWT", "REST APIs"],
      description: "A native iOS application for tracking vehicle maintenance history, managing vehicle profiles, and scheduling garage service appointments.",
      keyFeatures: [
        "Native iOS development with Swift and SwiftUI",
        "Vehicle maintenance tracking",
        "Garage service scheduling",
        "MongoDB backend integration",
        "JWT authentication",
        "REST API endpoints",
        "Modern declarative UI framework",
      ],
      tags: ["Swift", "SwiftUI", "NestJS", "MongoDB", "JWT", "REST APIs", "iOS", "Mobile Development", "Car Management"],
      github: "https://github.com/karhebti-app/karhebti-ios",
      linkStatus: "Link coming soon",
    },
    {
      name: "Karhebti Backend",
      fullTitle: "Karhebti Backend — Complete Car Management Platform API",
      period: "November 2025 – February 2026",
      platforms: "Node.js / NestJS",
      technologies: ["NestJS", "TypeScript", "MongoDB", "Mongoose", "JWT", "Socket.IO", "Firebase", "Twilio", "OpenStreetMap"],
      description: "Backend API for Karhebti platform handling authentication, vehicles, maintenance, documents, garages, marketplace, and real-time communication.",
      keyFeatures: [
        "JWT and Argon2 authentication with OTP flows",
        "Vehicle CRUD operations with image management",
        "Maintenance scheduling and recommendations",
        "Document upload with expiration monitoring",
        "Garage operations with geocoding",
        "Marketplace with buyer/seller conversations",
        "Real-time chat with Socket.IO",
        "Firebase push notifications and email delivery",
        "Swagger API documentation",
        "REST API with 30+ endpoints",
      ],
      tags: ["NestJS", "TypeScript", "MongoDB", "Mongoose", "JWT", "Socket.IO", "Firebase", "Twilio", "OpenStreetMap", "Backend", "API Development", "Authentication"],
      linkStatus: "Link coming soon",
    },
    {
      name: "Vet Contract",
      fullTitle: "Vet Contract — Ethereum Smart Contract for Veterinary Records",
      period: "June 2026 – August 2026",
      platforms: "Blockchain",
      technologies: ["Solidity", "Hardhat", "Sepolia", "Ethereum", "IPFS", "Smart Contract Security"],
      description: "Permissioned Ethereum smart contract for recording and verifying veterinary health events on-chain with permission-based access control and data integrity via hashing.",
      keyFeatures: [
        "Permission-based access control (owner, writers, readers)",
        "Hash-based storage for health event integrity",
        "IPFS metadata support",
        "Timestamp tracking for recording and updates",
        "On-chain verification of health events",
        "Granular read/write permissions",
        "Built with Solidity 0.8.20 and Hardhat",
      ],
      tags: ["Solidity", "Hardhat", "Sepolia", "Ethereum", "IPFS", "Smart Contract Security", "Blockchain", "Data Integrity", "Access Control"],
      linkStatus: "Link coming soon",
    },
    {
      name: "Arabsoft",
      fullTitle: "Arabsoft RN AI Assistant — Company Knowledge Chatbot",
      period: "June 2025 – August 2025",
      platforms: "React Native and Spring Boot",
      technologies: ["React Native", "Spring Boot", "Java", "REST API", "AI Chatbot", "Authentication", "Chatbot"],
      description: "Mobile AI assistant with React Native frontend and Spring Boot backend featuring secure authentication and prompt-tuned AI chatbot for instant company knowledge retrieval.",
      keyFeatures: [
        "React Native mobile application",
        "Spring Boot backend API",
        "Secure authentication and login flows",
        "AI-powered chatbot with prompt tuning",
        "Company knowledge base integration",
        "User authentication and authorization",
        "REST API endpoints",
      ],
      tags: ["React Native", "Spring Boot", "Java", "REST API", "AI Chatbot", "Authentication", "Mobile", "Backend", "AI/ML", "Chatbot"],
      linkStatus: "Link coming soon",
    },
    {
      name: "CI/CD AI Anomaly Detection",
      fullTitle: "CI/CD AI Anomaly Detection — Intelligent Pipeline Monitoring",
      period: "June 2026 – August 2026",
      platforms: "Python / DevOps",
      technologies: ["Python", "Flask", "GitHub Actions", "Docker", "Kubernetes", "Scikit-learn", "Pandas", "Docker Compose"],
      description: "AI-powered DevOps project that monitors CI/CD pipeline logs, detects anomalies using machine learning, and identifies failure patterns before they become recurring issues.",
      keyFeatures: [
        "CI/CD Pipeline Log Analysis",
        "Anomaly Detection using Isolation Forest",
        "Failure Pattern Identification",
        "Interactive Web Dashboard",
        "REST API for programmatic access",
        "Health Check Endpoint",
        "Docker Compose deployment",
        "Kubernetes-ready deployment",
        "Automated GitHub Actions workflows",
        "Approximately 15 hours per month saved through automation",
      ],
      tags: ["Python", "Flask", "GitHub Actions", "Docker", "Kubernetes", "Scikit-learn", "AIOps", "CI/CD", "Machine Learning", "DevOps", "Security", "Cloud"],
      github: "https://github.com/azizwhibi/ci-cd-ai-anomaly",
      linkStatus: "Link coming soon",
    },
  ],
  skills: {
    programmingLanguages: ["Java", "Python", "TypeScript", "JavaScript", "SQL", "Kotlin", "Swift"],
    backendAndApis: ["Node.js", "NestJS", "Spring Boot", "Flask", "REST APIs", "JWT", "Backend architecture", "API integration"],
    mobileDevelopment: ["React Native", "Flutter", "Kotlin", "Swift", "SwiftUI", "Native Android development", "Native iOS development", "Cross-platform mobile development", "Mobile UI/UX"],
    webDevelopment: ["React", "Next.js", "Symfony", "Progressive Web Applications"],
    databases: ["PostgreSQL", "MongoDB", "MySQL", "SQL data modelling", "Blockchain-oriented medical dossier concepts", "Data integrity and traceability concepts"],
    cicdAndDevops: ["Git", "GitHub Actions", "Docker", "Docker Compose", "Linux", "Jenkins", "CI/CD automation", "Deployment workflows", "Pipeline monitoring", "Diagnostic workflows"],
    engineeringPractices: ["Testing", "Debugging", "Monitoring", "Agile development", "Requirements analysis", "Iterative development", "Secure authentication"],
  },
  cicd: {
    title: "Improving Software Delivery Through Automation",
    description:
      "I have practical experience improving delivery pipelines through GitHub Actions automation, CI/CD data centralisation, pipeline diagnostics, Docker Compose health checks, monitoring workflows, anomaly detection workflows, testing, and debugging.",
    tunisieTelecomHighlights: [
      "Flask REST API and dashboard for centralised CI/CD data",
      "Four automated GitHub Actions workflows",
      "Metrics automation",
      "Anomaly detection workflow",
      "Deployment workflow",
      "Docker Compose health checks",
      "Pipeline diagnostic workflows",
      "Approximately 15 hours per month saved through automation",
    ],
    pipelineStages: ["Code", "Tests", "Security / Checks", "Metrics", "Deployment", "Monitoring"],
  },
  education: {
    espretEngineering: {
      location: "Ariana, Tunisia",
      program: "Engineering Cycle, Software Engineering Specialization",
      period: "September 2024 – Present",
      coursework: ["Software Architecture", "Distributed Systems", "Cloud Computing", "DevOps"],
    },
    espretPreparatory: {
      location: "Ariana, Tunisia",
      program: "Preparatory Cycle, Software Engineering Specialization",
      period: "September 2022 – June 2024",
    },
    lyceeJendouba: {
      location: "Jendouba, Tunisia",
      qualification: "Baccalaureate in Computer Science",
      year: "2022",
    },
    certification: {
      name: "AWS Certified Cloud Practitioner",
      year: "2026",
    },
  },
  languages: [
    { language: "Arabic", level: "Native" },
    { language: "French", level: "Fluent" },
    { language: "English", level: "Fluent" },
  ],
  chatbotKnowledgeBase: {
    generalProfile:
      "Aziz Ouhibi is a software engineering student at ESPRIT in Ariana, Tunisia. His primary focus is backend development, mobile development, CI/CD, DevOps practices, cloud computing, software quality, testing, debugging, and monitoring. He is an AWS Certified Cloud Practitioner.",
    wehacklabs:
      "Aziz has worked as a Part-Time Software Developer at WeHackLabs in Tunis, Tunisia since September 2025. His work includes feature delivery, testing, debugging, building a responsive Progressive Web App, requirements analysis, prioritisation, and Agile collaboration.",
    tunisietelecom:
      "Aziz was a Software Engineering Intern at Tunisie Telecom in Tunis, Tunisia from June 2026 to August 2026. He built a Flask REST API and dashboard to centralise CI/CD data. He automated four GitHub Actions workflows for metrics, anomaly detection, and deployment. He also created Docker Compose health checks and diagnostic workflows for CI/CD pipelines. These automated workflows saved approximately 15 hours per month.",
    ciCdAiAnomaly:
      "The CI/CD AI Anomaly Detection project is an AI-powered DevOps tool developed during Aziz's internship at Tunisie Telecom. It monitors CI/CD pipeline logs, detects anomalies using machine learning (Isolation Forest), and identifies failure patterns before they become recurring issues. It includes a Flask web dashboard, REST API, automated GitHub Actions workflows, and is Docker and Kubernetes ready. It saved approximately 15 hours per month through automation.",
    arabsoft:
      "Aziz was a Mobile Developer Intern at ArabSoft in Tunis, Tunisia from June 2025 to August 2025. He developed a complete React Native application in two months, from requirements through production. He implemented secure sign-up and login flows, built a chatbot covering more than five categories, and delivered 100% of planned features through iterative development and user feedback.",
    karhebti:
      "Karhebti is a cross-platform car management and maintenance application developed from November 2025 to February 2026. It supports Android and iOS. Aziz used Kotlin for Android, Swift and SwiftUI for iOS, NestJS for the backend, MongoDB for the database, JWT for authentication, and REST APIs. The project includes vehicle tracking, maintenance management, garage-related workflows, document management, authentication, and more than 15 REST endpoints.",
    vetaiAnimalia:
      "VetAI / Animalia is a veterinary platform for veterinarians and pet owners developed from February 2026 to June 2026. Aziz used Flutter, NestJS, Next.js, PostgreSQL, Docker, and REST APIs. It includes appointments, pet-care workflows, veterinarian and pet-owner interactions, authentication, scheduling, notifications, and more than 15 PostgreSQL-backed REST endpoints.",
    blockchain:
      "Aziz has blockchain-related experience through the VetAI / Animalia project. He worked on a blockchain-oriented approach for veterinary medical dossiers within the Flutter-based application. The purpose was to improve the integrity, traceability, and reliability of veterinary medical information.",
    blockchainDetailsUnavailable:
      "I know Aziz worked on a blockchain-oriented veterinary medical dossier concept in the Flutter-based VetAI / Animalia project, focused on data integrity and traceability. I don't have more specific implementation details yet.",
    planvent:
      "Planvent is an event management platform developed from January 2025 to June 2025. Aziz used Symfony, Java, Spring Boot, MySQL, Docker, REST APIs, and JWT. It includes web and desktop solutions for events, vendors, booking workflows, role-based JWT access control, REST APIs, and MySQL data models.",
    skills: {
      programming: "Java, Python, TypeScript, JavaScript, SQL, Kotlin, Swift.",
      backend: "Node.js, NestJS, Spring Boot, Flask, REST APIs, JWT.",
      webMobile: "React, Next.js, React Native, Flutter, Kotlin, Swift, SwiftUI, Symfony.",
      databases: "PostgreSQL, MongoDB, MySQL.",
      devops: "Git, GitHub Actions, Docker, Docker Compose, Linux, Jenkins, CI/CD automation, pipeline monitoring, diagnostic workflows.",
      practices: "Testing, debugging, monitoring, Agile development, requirements analysis, iterative development, secure authentication.",
    },
    education:
      "I am enrolled in the Engineering Cycle, Software Engineering Specialization, at ESPRIT in Ariana, Tunisia, from September 2024 to present. He completed the Preparatory Cycle, Software Engineering Specialization, at ESPRIT from September 2022 to June 2024. He earned a Baccalaureate in Computer Science from Lycée de Jendouba in 2022. Relevant coursework includes Software Architecture, Distributed Systems, Cloud Computing, and DevOps.",
    languages: "Arabic is Aziz's native language. French is fluent. English is fluent.",
    contact: "Email: ouhibi.aziz@esprit.tn\nPhone: +216 93 177 115\nLocation: Ariana, Tunisia\nGitHub: https://github.com/azizwhibi\nLinkedIn: https://www.linkedin.com/in/azizouhibi/",
    suggestedQuestions: [
      "Who is Aziz Ouhibi?",
      "What technologies does Aziz use?",
      "Tell me about Aziz's CI/CD experience.",
      "What did Aziz build at Tunisie Telecom?",
      "What is the CI/CD AI Anomaly Detection project?",
      "What mobile apps has Aziz developed?",
      "What is Karhebti?",
      "What is VetAI / Animalia?",
      "Does Aziz have blockchain experience?",
      "What did Aziz do with blockchain in VetAI?",
      "What backend technologies does Aziz use?",
      "Is Aziz AWS certified?",
      "What did Aziz build at ArabSoft?",
      "How can I contact Aziz?",
    ],
  },
} as const;
